- name: Save and use Cisco IOS facts
  hosts: router4 
  connection: ansible.netcommon.network_cli
  gather_facts: false
  tasks:
    - name: show username
      debug:
        msg: "idx: {{ idx }} - {{ user }}"
      loop: "{{ usernames }}" 
      loop_control:
        index_var: idx
        loop_var: "user"
        label: "show variables {{ user.name }}"

    - name: create username on devices
      ios_config:
        lines:
          - username {{ item.name }} privi {{ item.priv }} secret {{ item.secret }}
      loop: "{{ usernames }}"
